import FloatSpec.Test.BracketSource
import FloatSpec.Test.ArithmeticProperties
import FloatSpec.Test.FlocqConformance
import FloatSpec.Test.FIXDirect
import FloatSpec.Test.FLXDirect
import FloatSpec.Test.FLTDirect
import FloatSpec.Test.FTZSourceShape
import FloatSpec.Test.NativeBridgeBits
import FloatSpec.Test.NativeIEEE
import FloatSpec.Test.NativeArithmetic
import FloatSpec.Test.BitsExecution
import FloatSpec.Test.BitOrderExecution
import FloatSpec.Test.NativeSourceArithmetic
import FloatSpec.Test.RoundingWalkthrough
import FloatSpec.Test.CoqSourceLinks
import FloatSpec.Test.ZauxSource
import FloatSpec.Test.MagSource
import FloatSpec.Test.PffTotality
import FloatSpec.Test.PffSourceContracts
import FloatSpec.Test.PrimFloatSource
import FloatSpec.Test.ComputableCompareExecution
import FloatSpec.Test.RoundingModeSource
import FloatSpec.Test.SimprocRaux
import FloatSpec.Test.SourceCorrectnessAliases
